server:
  port: 8912
  servlet:
    encoding:
      charset: UTF-8
      force: true
    session:
      timeout: 1800
    
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1234
    
     