server:
  port: 8912
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      force: true

      
spring:
  profiles:
    include:
    - oauth
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: 1234
  mvc:
    view:
      prefix: /WEB-INF/interview/
      suffix: .jsp
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 936897899536-25e24gducu4n84e9iqn50meu1v7okpdm.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8912/api/page/home

#swagger
springdoc:
 version: '@project.version@'
 api-docs:
    path: /api-docs
 default-consumes-media-type: application/json
 default-produces-media-type: application/json
 swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    doc-expansion: none
 paths-to-match:
  - /api/** 
  
#security